#!/usr/bin/env babel-node --presets es2015

import tap from 'tap';
import csp from 'js-csp';
import {expect} from 'chai';
import * as te3270 from './../index';
import { screen, text, field } from './../screen';

tap.test('te3270', (t) => {
  t.test('should process streams', function(tt) {
    const terminal = te3270.connect('mustang.nevada.edu');
    const loginScreen = screen(terminal, {
      terminal: text([[3, 72], [3, 79]]),
      username: field([16, 33])
    });

    csp.go(function*() {
      yield terminal.command("wait()");
      yield loginScreen.username("foo");
      const text = yield loginScreen.terminal();
      yield terminal.command("quit()");

      expect(text).to.match(/TCP[0-9]+/);

      tt.done();
    });
  });

  t.done();
});
